Project: Covid-19 tweets Classification (NLP)
data:
  processed:
    data_size: 2000
    file: processed_tweets.csv
  raw:
    file: covid-19-tweets
  split:
    files:
    - train.csv
    - test.csv
    ratio: 0.25
    seed: 42
eda:
  path: ed-analytics/
models:
  baseline:
    file: model.pkl
    path: baselines
  cross_validation:
    model: logistic
    n_split: 10
    path: cross_valid/
    seed: 43
  hyper_tuner:
    method: grid
    num_split: 5
    path: src/model_checkpoints/tuned
    scoring_metrics:
    - f1_weighted
    - roc_auc_ovo
    seed: 43
    selected_cols:
    - params
    - mean_test_f1_weighted
    - mean_test_roc_auc_ovo
    - rank_test_roc_auc_ovo
    shuffle: true
  path: src/model_checkpoints
  seed: 43
  train:
    encoder: label_encoder.pkl
    metrics: metrics.json
    model: logistic
    optimize: true
    path: trained/
