---
Project: Covid-19 tweets Classification (NLP)

# Data Paths
data:
  raw: 
    path: data/raw/covid-19-tweets

  processed: 
    path: data/processed
    file: processed_tweets.csv

  split:
    path: data/split
    ratio: 0.2
    seed: 43
    files: 
      - train.csv
      - test.csv 

eda: 
    path: ed-analytics/

# Model Directories
models:
  seed: 43
  dev:
    path: models/
    file: model.pkl

  train:
    path: trained/
    model: logistic
    encoder: label_encoder.pkl
    metrics: metrics.json

  cross_validation:
    model: logistic
    n_splits: 5
    path: cross_valid/

  fine_tune:
    model: logistic
    n_splits: 3
    path: tuned/
