---
Project: Covid-19 tweets Classification (NLP)

# Data Paths
data:
  raw:
    path: data/raw/covid-19-tweets
  processed:
    data_size: 0 # Full data size -> 0
    path: data/processed
    file: processed_tweets.csv
  split:
    path: data/split
    ratio: 0.25
    seed: 42
    files:
      - train.csv
      - test.csv

eda:
    path: ed-analytics/

# Model Directories
models:
  seed: 43
  dev:
    path: models/central/
    file: model.pkl

  train:
    path: trained/
    model: logistic
    encoder: label_encoder.pkl
    metrics: metrics.json

  cross_validation:
    model: logistic
    n_splits: 5
    path: cross_valid/

  fine_tune:
    model: logistic
    n_splits: 3
    path: tuned/
