stages:
  process:
    cmd: python src/data_processing/data_preprocessing.py data/raw data/processed
    deps:
    - data/raw/covid-19-tweets
    - src/data_processing/data_preprocessing.py
    params:
    - configs.yml:
      - data.processed.data_size
    outs:
    - data/processed
  data_analysis:
    cmd: python src/data_processing/exploratory_analysis.py data/processed data/analytics
    deps:
    - data/processed
    - src/data_processing/exploratory_analysis.py
    outs:
    - data/analytics
  data_split:
    cmd: python src/data_processing/data_splitting.py data/processed data/split
    deps:
    - data/processed
    - src/data_processing/data_splitting.py
    params:
    - configs.yml:
      - data.split.ratio
      - data.split.seed
    outs:
    - data/split
  baseline_model:
    cmd: python src/model_development/baseline_model.py src/model_checkpoints/baselines
    deps:
    - src/model_development/baseline_model.py
    params:
    - configs.yml:
      - models.seed
    outs:
    - src/model_checkpoints/baselines
  training:
    cmd: python src/model_development/model_training.py data/split src/model_checkpoints/trained
    deps:
    - data/split
    - src/model_development/model_training.py
    params:
    - configs.yml:
      - models.train.model
    outs:
    - src/model_checkpoints/trained
  # cross_validation:
  #   cmd: python src/model_optimization/cross_validation.py data/split src/model_checkpoints/cross_valid
  #   deps:
  #   - data/split
  #   - src/model_optimization/cross_validation.py
  #   params:
  #   - configs.yml:
  #     - models.cross_validation.model
  #     - models.cross_validation.n_split
  #   outs:
  #   - src/model_checkpoints/cross_valid
  # hyper_optimizer:
  #   cmd: python src/model_optimization/hyper_opt.py data/split
  #   deps:
  #   - data/split
  #   - src/model_optimization/hyper_opt.py
  #   params:
  #   - configs.yml:
  #     - models.train.optimize
  #   outs:
  #   - src/model_checkpoints/tuned
