project: Covid-19 tweets Classification (NLP)
data:
  clean:
    path: data/raw/covid-19-tweets

  processed:
    path: data/processed
    file: processed_tweets.csv

  analysis:
    path: analytics/

  split:
    path: data/split
    ratio: 0.2
    seed: 43
    file:
      - train.csv
      - test.csv

dev:
  path: models/
  file: model.pkl

  train:
    path: trained/
    model: logistic
    encoder: label_encoder.pkl
    metric: metrics.json

  cross-valid:
    model: logistic
    n_split: 5
    path: cross_val/
    file: model.pkl

  fine-tune:
    model: logistic
    n_split: 3
    path: tuned/
