data:
  processed:
    - covid19_tweets.csv
  split:
    - train.csv
    - test.csv

cross_valid:
  model: vote

model_attrs:
  file: model.pkl
  tune_optimizer:
    type: lr
    n_split: 3
    tuned_out: tuned_params

  cross_valid:
    type: vote # options -> ["vote", "lr", "bayes", "svm", "rf", "tree"]

training:
  model: logisticregression
  path_in: models/
  path_out: evaluate/